services:
  qiandao:
    image: a76yyyy/qiandao:latest
    container_name: qiandao
    restart: always
    depends_on:
      - redis
    ports:
      - "127.0.0.1:${QIANDAO_PORT:-8923}:80"
    volumes:
      - "${QIANDAO_CONFIG}:/usr/src/app/config"
    environment:
      - QIANDAO_DEBUG=False
      - DOMAIN=${DOMAIN}
      - REDISCLOUD_URL=redis://redis:6379
      - DB_TYPE=sqlite3
      - PBKDF2_ITERATIONS=400
      - AES_KEY=${AES_KEY}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - MAIL_SMTP=${MAIL_SMTP}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_USER}
  redis:
    image: redis:8.10-alpine
    container_name: qiandao-redis
    restart: always
    command: ["--loglevel", "warning"]
    volumes:
      - "${REDIS_DATA}:/data"
