services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: always
    ports:
      - "8083:8083"
    volumes:
      - /home/einverne/calibre-web/config:/config
      - /home/einverne/Syncthing/CalibreBooks:/books
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
