version: '3.7'
services:
  worker:
    image: leishi1313/aurora-admin-backend:latest
    restart: always
    command: bash worker.sh
    environment:
      - DATABASE_URL=${DB_URL}
      - TRAFFIC_INTERVAL_SECONDS=600
      - DDNS_INTERVAL_SECONDS=120
    volumes:
      - $HOME/.ssh/id_ed25519:/app/ansible/env/ssh_key
      - ~/aurora/app-data:/app/ansible/priv_data_dirs
    depends_on:
      - redis

  backend:
    image: leishi1313/aurora-admin-backend:latest
    restart: always
    command: bash -c "while !</dev/tcp/postgres/5432; do sleep 1; done; alembic upgrade heads && python app/main.py"
    environment:
      - PYTHONPATH=.
      - DATABASE_URL=${DB_URL}
      - SECREY_KEY=${SECREY_KEY}
    volumes:
      - ~/aurora/app-data:/app/ansible/priv_data_dirs
    depends_on:
      - postgres
      - redis

  nginx:
    image: leishi1313/aurora-admin-frontend:latest
    restart: always
    ports:
      - 8000:80
    depends_on:
      - backend

  redis:
    image: redis
    restart: always

  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ~/aurora/db-data:/var/lib/postgresql/data

