version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    tmpfs:
      - /tmp
      - /var/run/postgresql
    env_file:
      - .env
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
  mattermost:
    container_name: mattermost
    image: mattermost/mattermost-team-edition:latest
    restart: unless-stopped
    depends_on:
      - postgres
    security_opt:
      - no-new-privileges:true
    pids_limit: 200
    tmpfs:
      - /tmp
    env_file:
      - .env
    ports:
      - 127.0.0.1:8065:8065
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - ./volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/app/mattermost/client/plugins:/mattermost/client/plugins:rw
      - ./volumes/app/mattermost/bleve-indexes:/mattermost/bleve-indexes:rw

